# Generated by Django 3.2.7 on 2023-11-29 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riasec', '0017_alter_result_user'),
        ('personalityTest', '0027_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedprogram',
            name='offeredProgram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riasec.offeredprogram'),
        ),
    ]
